### ISSUE TITLE
New Free42 Functions

### ISSUE THREAD

**Issue by grubmueller** [heilingbrunner/vscode-hp42s-free42#6]
Using your plugin is in my opinion the best way to write programs for the Free42 platform. Thomas Okken, the father of Free42, added (and still adds) some great new functions to the calculator. The new comparison function in 3.0.1 release seem very promising! Is your project still active? Do you plan to add the new functions to your plugin?

**Comment by grubmueller** [comment]
Sorry, didn't want to create an issue on git. Wasn't sure how to contact.

**Comment by heilingbrunner** [comment]
Thank you for this. I already added new functions from former versions. I will see and check.
